
& C:/Users/Dagurlkc/anaconda3/python.exe c:/TheTradingRobotPlug/Tests/Data_Fetch/test_gui.py
PS C:\TheTradingRobotPlug> & C:/Users/Dagurlkc/anaconda3/python.exe c:/TheTradingRobotPlug/Tests/Data_Fetch/test_gui.py
.c:\TheTradingRobotPlug\Scripts\Utilities\data_fetch_utils.py:13: ResourceWarning: unclosed file <_io.TextIOWrapper name='C:\\TheTradingRobotPlug\\logs\\data_store.log' mode='a' 
encoding='cp1252'>                                                                                                                                                                  self.logger = self.setup_logger("DataFetchUtils", log_file)  # Initialize logger after directory check
ResourceWarning: Enable tracemalloc to get the object allocation traceback
..c:\TheTradingRobotPlug\Scripts\Utilities\data_fetch_utils.py:13: ResourceWarning: unclosed file <_io.TextIOWrapper name='C:\\TheTradingRobotPlug\\logs\\data_store.log' mode='a'
 encoding='cp1252'>                                                                                                                                                                 self.logger = self.setup_logger("DataFetchUtils", log_file)  # Initialize logger after directory check
ResourceWarning: Enable tracemalloc to get the object allocation traceback
....
----------------------------------------------------------------------
Ran 7 tests in 0.115s

OK
